@extends('layouts.app')
@section('title', 'Contact us')
@section('content')
    <br><br>
    <div class="container">
    <p style="line-height: normal;"><strong><span style="font-size: 22.0pt; font-family: Arial;">Allgemeine Gesch&auml;ftsbedingungen</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Geltungsbereich</span></strong></p>
    <p style="line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Gesellschaft mit beschr&auml;nkter Haftung MP Soft GmbH, Weinbergstrasse 8, 8807 Freienbach</span><span style="font-size: 12.0pt; font-family: Arial;"> bietet ihren Kunden </span><span style="font-size: 12.0pt; font-family: Arial;">durch das Portal www.ullalla.ch </span><span style="font-size: 12.0pt; font-family: Arial;">die M&ouml;glichkeit an, </span><span style="font-size: 12.0pt; font-family: Arial;">eigene Profile anzulegen, Inhalte hochzuladen und damit f&uuml;r sich in diesem Portal Werbung zu machen. </span></p>
    <p style="line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die folgenden Allgemeinen Gesch&auml;ftsbedingungen (AGB) gelten f&uuml;r alle Dienstleistungen des Anbieters.</span></p>
    <p style="line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Kunden, die eine Dienstleistung, des Anbieters in Anspruch nehmen, anerkennen damit diese AGB.</span></p>
    <p style="line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Regelungen und Bedingungen, die von dieser AGB abweichen, werden zwischen dem Anbieter und den betreffenden Kunden schriftlich vereinbart.</span></p>
    <p style="line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Angebot</span></strong><strong><span style="font-size: 12.0pt; font-family: Arial;"> und Vertragsabschluss</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Der Vertrag zwischen dem Kunden und der Dienstanbieterin kommt formfrei durch die Inanspruchnahme der Dienstleistungen gem. Art. 4 Abs. 2 OR (Obligationenrecht) zustande<br /> <br /> </span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Der Vertrag tritt in Kraft, wenn die &Uuml;berweisung und der Erhalt des zu bezahlenden Betrages an ullalla.ch erfolgreich abgeschlossen ist.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Ullalla.ch beh&auml;lt sich das Recht vor, Vertragsabschl&uuml;sse ohne Angabe von Gr&uuml;nden zu verweigern.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Der Vertrag gilt solange, wieviel der Kunde die Dienstleistung von ullalla.ch angesprochen hat. Bei Beendigung der Werbefrist ist der Vertrag beendet und tritt erst wieder in Kraft, wenn der Kunde die Dienstleistungen von ullalla.ch wieder bezieht.</span></p>
    <p style="line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Benutzerkonto und Inserate</span></strong></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Der Nutzer des Portals ullalla.ch muss sich kostenlos registrieren. Bei der Registrierung w&auml;hlen die Nutzer einen Benutzernamen und ein Passwort. Die Nutzer erhalten ein pers&ouml;nliches Konto im Portal. Die Nutzer erhalten nach der Registrierung eine Best&auml;tigungsmail, dass Ihr Konto freigeschalten worden ist</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Ullalla.ch unterscheidet zwei Arten von Kunden. Die einen sind Lokale, die durch Ihr Konto mehrere Arbeiter/innen durch ihr Lokal anmelden k&ouml;nnen. Die anderen Kunden sind private Arbeiter/innen, die nur ein Account pro Person anlegen d&uuml;rfen.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Sollte es bei einem Verstoss der Regeln dieser AGB kommen, behaltet sich ullalla.ch vor die Benutzerkonten sofort zu l&ouml;schen. Alle Nutzer dieses Portals m&uuml;ssen &uuml;ber 18 Jahre alt sein, sobald dies nicht der Fall ist, nimmt sich ullalla.ch das Recht vor, das Konto zu l&ouml;schen und evtl. zu sperren.</span></p>
    <p style="margin-left: 54.0pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Inseratebilder d&uuml;rfen keine sexuelle Handlungen mit Kindern oder Tieren beinhalten, sowie d&uuml;rfen menschlichen Ausscheidungen, Geschlechtsteilen und Geschlechtshandlungen nicht sichtbar sein.(SR 311.0 Art. 197 4)</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Bei der &Uuml;berpr&uuml;fung der Inseratebilder beh&auml;lt sich ullalla.ch das Recht vor, die Bilder nicht zu ver&ouml;ffentlichen und bei einem schwerem Fall wie z.B. Sexuelle Handlungen mit Kindern oder Tieren, auch wenn es nur im Text steht, sogar Anzeige zu erstatten und es als eine Straftat zu behandeln.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Ullalla.ch entzieht sich jeglicher Verantwortung aufgrund dieser Gesetzeslage.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Der Nutzer des Portals ullalla.ch verpflichtet sich alle Angaben &uuml;ber sich wahrheitsgem&auml;ss auszuf&uuml;llen.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Wer Anzeigen auf das Portal von ullalla.ch erstellen m&ouml;chte ist verpflichtet die folgenden Bestimmungen und Angaben zu beachten.</span></p>
    <ul>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Datenschutzgesetz (DSG)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Fernmeldegesetz (FMG)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Obligationenrecht (OR)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Preisbekanntverordnung (PBV)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Weisungen von Swissmedic</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Und das Strafgesetzbuch (StGB)</span></li>
    </ul>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Rechtswidrig sind insbesondere:</span></p>
    <ul>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Gewaltdarstellungen (Art. 135 StGB)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Rassendiskriminierung (Art. 261bis StGB)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Aufruf zur Gewalt (Art. 259 StGB)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Unerlaubtes Gl&uuml;cksspiel (Spielbanken- und Lotteriegesetz)</span></li>
        <li style="margin-left: 21.0pt; text-indent: -21.0pt; line-height: normal; tab-stops: 21.0pt;"><span style="font-size: 12.0pt; font-family: Arial;">Das Anbieten von pornographischen Diensten (Art. 197 Ziff. 3. Und 3bis im StGB)</span></li>
    </ul>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Solche Inhalte d&uuml;rfen auch nicht Erwachsenen zug&auml;nglich gemacht werden, die einen verbotenen Inhalt von sich aus nachgefragt haben. Strikt verboten ist die Ver&ouml;ffentlichung von Fotos, Abbildungen, Bildfolgen, Illustrationen, Skizzen, Zeichnungen, Comics, Animationen, Trailern, Videos, Videoclips, Teasern, Texten, Anzeigen, Postern, Bannern, Links, SMS-Botschaften, MMS-Botschaften, E-Mail-Botschaften, Attachments sowie Darstellungen oder Texte, die auf sexuelle Handlungen mit Kindern oder mit Tieren, auf menschliche Ausscheidungen oder Gewaltt&auml;tigkeiten hinweisen oder diese zeigen. Aufgrund der Beschr&auml;nkungen, die die Dienstanbieterin durch das Datenschutzgesetz (DSG) und die Bundesverfassung (BV) auferlegt sind, kann die Dienstanbieterin keine Haftung daf&uuml;r &uuml;bernehmen, dass missbr&auml;uchlich handelnde Anbieter f&uuml;r verbotene Inhalte in den Publikationen von der Dienstanbieterin werben. Sollte die Dienstanbieterin feststellen, dass gesetzwidrige Informationen zur Verf&uuml;gung gestellt werden, so ist diese berechtigt, fehlbare Kunden von der weiteren Inanspruchnahme ihrer Dienstleistungen ohne Mitteilung auszuschliessen. Sollte die Dienstanbieterin feststellen, dass Inserentinnen oder Inserenten den Konsumenten gesetzeswidrige Inhalte anbieten oder zur Verf&uuml;gung stellen, so ist die Dienstanbieterin berechtigt, Strafanzeige zu erstatten und die f&uuml;r den Missbrauch Verantwortlichen von jeder weiteren Gesch&auml;ftsverbindung auszuschliessen. In gleicher Weise wird die Dienstanbieterin handeln, wenn Inserentinnen oder Inserenten gegen die Bestimmungen zur Beachtung des Schutzalters </span><span style="font-size: 12.0pt; font-family: Arial;">(18) </span><span style="font-size: 12.0pt; font-family: Arial;">verstossen.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Widerrufsrecht</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Vertragserkl&auml;rung kann innert 7 Tagen nach Vertragsabschluss durch schriftliche Einreichung per Email oder Brief an ullalla.ch gek&uuml;ndigt werden.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Bei einer wirksamen K&uuml;ndigung sind jedoch die schon geleisteten Dienstleistungen&nbsp; von ullalla.ch zu bezahlen und werden nicht zur&uuml;ckerstattet.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Spam</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Das Senden von Werbebotschaften f&uuml;r andere Webseiten sowie das Abwerben von Kunden ist strengstens untersagt.</span><span style="font-size: 12.0pt; font-family: Arial;"> Bei s&auml;mtlichen </span><span style="font-size: 12.0pt; font-family: Arial;">Versuchen dieser genannten Werbebotschaften, </span><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;beh&auml;lt sich </span><span style="font-size: 12.0pt; font-family: Arial;">ullalla</span><span style="font-size: 12.0pt; font-family: Arial;">.ch das Recht vor, bei wiederholten Zuwiederhandlungen Anzeige zu erstatten. Dies gilt auch f&uuml;r das </span><span style="font-size: 12.0pt; font-family: Arial;">S</span><span style="font-size: 12.0pt; font-family: Arial;">enden von Spam in jeglicher Form.<br /> <br /> Rechtliche Schritte gegen die Versender von so genannten Spam Mails sind ausdr&uuml;cklich vorbehalten</span><span style="font-size: 12.0pt; font-family: Arial;">.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 10.5pt;">&nbsp;</span></p>
    <p style="line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Zahlungsbedingungen</span></strong><strong><span style="font-size: 12.0pt; font-family: Arial;"> und Haftungsausschluss</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Dienstleistung von ullalla.ch erfolgt durch get&auml;tigter Zahlung durch die zur Verf&uuml;gung stehender Zahlungsm&ouml;glichkeiten (Kreditkartenzahlung).</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die genutzten technischen Einrichtungen von ullalla.ch entsprechen dem heutigen Stand.Ullalla.ch ist bem&uuml;ht den Stand der Technik immer auf den h&ouml;chsten Niveau zu halten. Ullalla.ch haftet nicht f&uuml;r Folgen im Falle eines Unterbruchs des Internets oder durch technische Probleme evtl. verschulden von Dritten. Jegliche Anspr&uuml;che des Kunden an ullalla.ch sind ausgeschlossen. </span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Angaben der Profile, sowie Aktualit&auml;t, Korrektheit, Vollst&auml;ndigkeit oder Qualit&auml;t der angegebenen Informationen sind ohne Gew&auml;hr. Jegliche Anspr&uuml;che auf Schadenersatz gegen ullalla.ch sind ausgeschlossen, sofern seitens des Nutzers kein nachweislich vors&auml;tzliches oder grob fahrl&auml;ssiges Verschulden vorliegt.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Alle Angebote von ullalla.ch sind unverbindlich und freibleibend.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Datenschutz</span></strong><strong><span style="font-size: 12.0pt; font-family: Arial;"> und Datensicherung</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></strong></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Datenschutzerkl&auml;rung ist integraler und bindender Teil dieser AGB.<br /> Die Daten werden gem&auml;ss schweizerischem Datenschutzgesetz sorgf&auml;ltig behandel</span><span style="font-size: 12.0pt; font-family: Arial;">t.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Bei L&ouml;schung des Kundenkontos werden s&auml;mtliche Daten des Kunden gel&ouml;scht und nicht an Dritte weitergegeben. Ullalla.ch garantiert bei Cyber-Angriffen keine Sicherung der Daten.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">&nbsp;</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Anwendbares Recht und Gerichtsstand</span></strong></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Die Rechtsbeziehungen zwischen </span><span style="font-size: 12.0pt; font-family: Arial;">ullalla</span><span style="font-size: 12.0pt; font-family: Arial;">.ch und dem </span><span style="font-size: 12.0pt; font-family: Arial;">Kunden</span><span style="font-size: 12.0pt; font-family: Arial;"> unterliegen ausschliesslich schweizerischem Recht. <strong>Gerichtsstand ist </strong></span><strong><span style="font-size: 12.0pt; font-family: Arial;">Kanton Schwyz, Bezirkgericht H&ouml;fe</span></strong><span style="font-size: 12.0pt; font-family: Arial;"> und dies unabh&auml;ngig davon</span><span style="font-size: 12.0pt; font-family: Arial;">, </span><span style="font-size: 12.0pt; font-family: Arial;">von wo aus d</span><span style="font-size: 12.0pt; font-family: Arial;">er Kunde die Dienstleistungen in Anspruch nimmt.</span></p>
    <p style="margin-bottom: .0001pt; line-height: normal;"><strong><span style="font-size: 12.0pt; font-family: Arial;">Vorbehalte</span></strong></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Sollten einzelne Bestimmungen dieser AGB ganz oder teilweise nichtig und/oder unwirksam sein, bleibt die G&uuml;ltigkeit und/oder Wirksamkeit der &uuml;brigen Bestimmungen oder Teile solcher Bestimmungen unber&uuml;hrt. Die ung&uuml;ltigen und/oder unwirksamen Bestimmungen werden durch solche ersetzt, die dem Sinn und Zweck der ung&uuml;ltigen und/oder unwirksamen Bestimmungen in rechtwirksamer Weise wirtschaftlich am n&auml;chsten kommt. Das gleiche gilt bei eventuellen L&uuml;cken dieser AGB.</span></p>
    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: Arial;">Alle Preise sind vorbehalten.</span></p>
    </div>
@stop